apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zsong0348-pixel/hello-k8s-cicd.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
