apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
  namespace: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - name: hello-k8s
          image: ghcr.io/zsong0348-pixel/hello-k8s:2eeee0eb84657d3dffce4e263c6554db6568ef50
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_VERSION
              value: "2eeee0eb84657d3dffce4e263c6554db6568ef50"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
